apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: cookies-appid-to-body
  namespace: kube-system
spec:
  cookiesToBody:
    cookieNames:
      - AppID

---

apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: cookies-userid-to-body
  namespace: kube-system
spec:
  cookiesToBody:
    cookieNames:
      - UserID

---

apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: cookies-session-to-body
  namespace: kube-system
spec:
  cookiesToBody:
    cookieNames:
      - Session

---

apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: common-headers
  namespace: kube-system
spec:
  headers:
    accessControlAllowMethods:
      - "GET"
      - "POST"
      - "OPTIONS"
      - "HEAD"
      - "PUT"
      - "DELETE"
      - "TRACE"
      - "PATCH"
    accessControlAllowCredentials: TRUE
    accessControlMaxAge: 100
    addVaryHeader: true

---

apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: http-redirect-https-testing
  namespace: kube-system
spec:
  redirectRegex:
    regex: ^http://([-a-zA-Z0-9|.]*):8080/(.*)
    replacement: https://${1}:38443/${2}

---

apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: http-redirect-https
  namespace: kube-system
spec:
  redirectRegex:
    regex: ^http://([-a-zA-Z0-9|.]*)/(.*)
    replacement: https://${1}/${2}
